/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTurnstileSiteKeyRouteImport } from './routes/api/turnstile.site-key'
import { Route as ApiContributionsUpsertRouteImport } from './routes/api/contributions.upsert'
import { Route as ApiMasjidsMasjidIdQrisRouteImport } from './routes/api/masjids.$masjidId.qris'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth.google.start'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnstileSiteKeyRoute = ApiTurnstileSiteKeyRouteImport.update({
  id: '/api/turnstile/site-key',
  path: '/api/turnstile/site-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContributionsUpsertRoute = ApiContributionsUpsertRouteImport.update({
  id: '/api/contributions/upsert',
  path: '/api/contributions/upsert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasjidsMasjidIdQrisRoute = ApiMasjidsMasjidIdQrisRouteImport.update({
  id: '/api/masjids/$masjidId/qris',
  path: '/api/masjids/$masjidId/qris',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/contributions/upsert': typeof ApiContributionsUpsertRoute
  '/api/turnstile/site-key': typeof ApiTurnstileSiteKeyRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/masjids/$masjidId/qris': typeof ApiMasjidsMasjidIdQrisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/contributions/upsert': typeof ApiContributionsUpsertRoute
  '/api/turnstile/site-key': typeof ApiTurnstileSiteKeyRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/masjids/$masjidId/qris': typeof ApiMasjidsMasjidIdQrisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/contributions/upsert': typeof ApiContributionsUpsertRoute
  '/api/turnstile/site-key': typeof ApiTurnstileSiteKeyRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/masjids/$masjidId/qris': typeof ApiMasjidsMasjidIdQrisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/contributions/upsert'
    | '/api/turnstile/site-key'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/masjids/$masjidId/qris'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/contributions/upsert'
    | '/api/turnstile/site-key'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/masjids/$masjidId/qris'
  id:
    | '__root__'
    | '/'
    | '/api/contributions/upsert'
    | '/api/turnstile/site-key'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/masjids/$masjidId/qris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiContributionsUpsertRoute: typeof ApiContributionsUpsertRoute
  ApiTurnstileSiteKeyRoute: typeof ApiTurnstileSiteKeyRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
  ApiMasjidsMasjidIdQrisRoute: typeof ApiMasjidsMasjidIdQrisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turnstile/site-key': {
      id: '/api/turnstile/site-key'
      path: '/api/turnstile/site-key'
      fullPath: '/api/turnstile/site-key'
      preLoaderRoute: typeof ApiTurnstileSiteKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contributions/upsert': {
      id: '/api/contributions/upsert'
      path: '/api/contributions/upsert'
      fullPath: '/api/contributions/upsert'
      preLoaderRoute: typeof ApiContributionsUpsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masjids/$masjidId/qris': {
      id: '/api/masjids/$masjidId/qris'
      path: '/api/masjids/$masjidId/qris'
      fullPath: '/api/masjids/$masjidId/qris'
      preLoaderRoute: typeof ApiMasjidsMasjidIdQrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiContributionsUpsertRoute: ApiContributionsUpsertRoute,
  ApiTurnstileSiteKeyRoute: ApiTurnstileSiteKeyRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
  ApiMasjidsMasjidIdQrisRoute: ApiMasjidsMasjidIdQrisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
