/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMasjidsRouteImport } from './routes/api/masjids'
import { Route as ApiTurnstileSiteKeyRouteImport } from './routes/api/turnstile.site-key'
import { Route as ApiQrisImagesQrisIdRouteImport } from './routes/api/qris-images/$qrisId'
import { Route as ApiPmtilesArchiveRouteImport } from './routes/api/pmtiles/$archive'
import { Route as ApiMasjidsSearchRouteImport } from './routes/api/masjids.search'
import { Route as ApiMasjidsMasjidIdRouteImport } from './routes/api/masjids.$masjidId'
import { Route as ApiContributionsUpsertRouteImport } from './routes/api/contributions.upsert'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth.session'
import { Route as ApiAdminReportsRouteImport } from './routes/api/admin.reports'
import { Route as ApiAdminQrisBackfillRouteImport } from './routes/api/admin.qris-backfill'
import { Route as ApiAdminPendingQrisRouteImport } from './routes/api/admin.pending-qris'
import { Route as ApiAdminConfigHealthRouteImport } from './routes/api/admin.config-health'
import { Route as ApiQrisQrisIdReportsRouteImport } from './routes/api/qris.$qrisId.reports'
import { Route as ApiMasjidsMasjidIdQrisRouteImport } from './routes/api/masjids.$masjidId.qris'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth.google.start'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'
import { Route as ApiAdminReportsReportIdResolveRouteImport } from './routes/api/admin.reports.$reportId.resolve'
import { Route as ApiAdminPendingQrisQrisIdResolveRouteImport } from './routes/api/admin.pending-qris.$qrisId.resolve'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasjidsRoute = ApiMasjidsRouteImport.update({
  id: '/api/masjids',
  path: '/api/masjids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnstileSiteKeyRoute = ApiTurnstileSiteKeyRouteImport.update({
  id: '/api/turnstile/site-key',
  path: '/api/turnstile/site-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrisImagesQrisIdRoute = ApiQrisImagesQrisIdRouteImport.update({
  id: '/api/qris-images/$qrisId',
  path: '/api/qris-images/$qrisId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPmtilesArchiveRoute = ApiPmtilesArchiveRouteImport.update({
  id: '/api/pmtiles/$archive',
  path: '/api/pmtiles/$archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasjidsSearchRoute = ApiMasjidsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiMasjidsRoute,
} as any)
const ApiMasjidsMasjidIdRoute = ApiMasjidsMasjidIdRouteImport.update({
  id: '/$masjidId',
  path: '/$masjidId',
  getParentRoute: () => ApiMasjidsRoute,
} as any)
const ApiContributionsUpsertRoute = ApiContributionsUpsertRouteImport.update({
  id: '/api/contributions/upsert',
  path: '/api/contributions/upsert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportsRoute = ApiAdminReportsRouteImport.update({
  id: '/api/admin/reports',
  path: '/api/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQrisBackfillRoute = ApiAdminQrisBackfillRouteImport.update({
  id: '/api/admin/qris-backfill',
  path: '/api/admin/qris-backfill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPendingQrisRoute = ApiAdminPendingQrisRouteImport.update({
  id: '/api/admin/pending-qris',
  path: '/api/admin/pending-qris',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigHealthRoute = ApiAdminConfigHealthRouteImport.update({
  id: '/api/admin/config-health',
  path: '/api/admin/config-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrisQrisIdReportsRoute = ApiQrisQrisIdReportsRouteImport.update({
  id: '/api/qris/$qrisId/reports',
  path: '/api/qris/$qrisId/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasjidsMasjidIdQrisRoute = ApiMasjidsMasjidIdQrisRouteImport.update({
  id: '/qris',
  path: '/qris',
  getParentRoute: () => ApiMasjidsMasjidIdRoute,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportsReportIdResolveRoute =
  ApiAdminReportsReportIdResolveRouteImport.update({
    id: '/$reportId/resolve',
    path: '/$reportId/resolve',
    getParentRoute: () => ApiAdminReportsRoute,
  } as any)
const ApiAdminPendingQrisQrisIdResolveRoute =
  ApiAdminPendingQrisQrisIdResolveRouteImport.update({
    id: '/$qrisId/resolve',
    path: '/$qrisId/resolve',
    getParentRoute: () => ApiAdminPendingQrisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/masjids': typeof ApiMasjidsRouteWithChildren
  '/api/admin/config-health': typeof ApiAdminConfigHealthRoute
  '/api/admin/pending-qris': typeof ApiAdminPendingQrisRouteWithChildren
  '/api/admin/qris-backfill': typeof ApiAdminQrisBackfillRoute
  '/api/admin/reports': typeof ApiAdminReportsRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/contributions/upsert': typeof ApiContributionsUpsertRoute
  '/api/masjids/$masjidId': typeof ApiMasjidsMasjidIdRouteWithChildren
  '/api/masjids/search': typeof ApiMasjidsSearchRoute
  '/api/pmtiles/$archive': typeof ApiPmtilesArchiveRoute
  '/api/qris-images/$qrisId': typeof ApiQrisImagesQrisIdRoute
  '/api/turnstile/site-key': typeof ApiTurnstileSiteKeyRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/masjids/$masjidId/qris': typeof ApiMasjidsMasjidIdQrisRoute
  '/api/qris/$qrisId/reports': typeof ApiQrisQrisIdReportsRoute
  '/api/admin/pending-qris/$qrisId/resolve': typeof ApiAdminPendingQrisQrisIdResolveRoute
  '/api/admin/reports/$reportId/resolve': typeof ApiAdminReportsReportIdResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/masjids': typeof ApiMasjidsRouteWithChildren
  '/api/admin/config-health': typeof ApiAdminConfigHealthRoute
  '/api/admin/pending-qris': typeof ApiAdminPendingQrisRouteWithChildren
  '/api/admin/qris-backfill': typeof ApiAdminQrisBackfillRoute
  '/api/admin/reports': typeof ApiAdminReportsRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/contributions/upsert': typeof ApiContributionsUpsertRoute
  '/api/masjids/$masjidId': typeof ApiMasjidsMasjidIdRouteWithChildren
  '/api/masjids/search': typeof ApiMasjidsSearchRoute
  '/api/pmtiles/$archive': typeof ApiPmtilesArchiveRoute
  '/api/qris-images/$qrisId': typeof ApiQrisImagesQrisIdRoute
  '/api/turnstile/site-key': typeof ApiTurnstileSiteKeyRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/masjids/$masjidId/qris': typeof ApiMasjidsMasjidIdQrisRoute
  '/api/qris/$qrisId/reports': typeof ApiQrisQrisIdReportsRoute
  '/api/admin/pending-qris/$qrisId/resolve': typeof ApiAdminPendingQrisQrisIdResolveRoute
  '/api/admin/reports/$reportId/resolve': typeof ApiAdminReportsReportIdResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/masjids': typeof ApiMasjidsRouteWithChildren
  '/api/admin/config-health': typeof ApiAdminConfigHealthRoute
  '/api/admin/pending-qris': typeof ApiAdminPendingQrisRouteWithChildren
  '/api/admin/qris-backfill': typeof ApiAdminQrisBackfillRoute
  '/api/admin/reports': typeof ApiAdminReportsRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/contributions/upsert': typeof ApiContributionsUpsertRoute
  '/api/masjids/$masjidId': typeof ApiMasjidsMasjidIdRouteWithChildren
  '/api/masjids/search': typeof ApiMasjidsSearchRoute
  '/api/pmtiles/$archive': typeof ApiPmtilesArchiveRoute
  '/api/qris-images/$qrisId': typeof ApiQrisImagesQrisIdRoute
  '/api/turnstile/site-key': typeof ApiTurnstileSiteKeyRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/masjids/$masjidId/qris': typeof ApiMasjidsMasjidIdQrisRoute
  '/api/qris/$qrisId/reports': typeof ApiQrisQrisIdReportsRoute
  '/api/admin/pending-qris/$qrisId/resolve': typeof ApiAdminPendingQrisQrisIdResolveRoute
  '/api/admin/reports/$reportId/resolve': typeof ApiAdminReportsReportIdResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/masjids'
    | '/api/admin/config-health'
    | '/api/admin/pending-qris'
    | '/api/admin/qris-backfill'
    | '/api/admin/reports'
    | '/api/auth/session'
    | '/api/contributions/upsert'
    | '/api/masjids/$masjidId'
    | '/api/masjids/search'
    | '/api/pmtiles/$archive'
    | '/api/qris-images/$qrisId'
    | '/api/turnstile/site-key'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/masjids/$masjidId/qris'
    | '/api/qris/$qrisId/reports'
    | '/api/admin/pending-qris/$qrisId/resolve'
    | '/api/admin/reports/$reportId/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/masjids'
    | '/api/admin/config-health'
    | '/api/admin/pending-qris'
    | '/api/admin/qris-backfill'
    | '/api/admin/reports'
    | '/api/auth/session'
    | '/api/contributions/upsert'
    | '/api/masjids/$masjidId'
    | '/api/masjids/search'
    | '/api/pmtiles/$archive'
    | '/api/qris-images/$qrisId'
    | '/api/turnstile/site-key'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/masjids/$masjidId/qris'
    | '/api/qris/$qrisId/reports'
    | '/api/admin/pending-qris/$qrisId/resolve'
    | '/api/admin/reports/$reportId/resolve'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/masjids'
    | '/api/admin/config-health'
    | '/api/admin/pending-qris'
    | '/api/admin/qris-backfill'
    | '/api/admin/reports'
    | '/api/auth/session'
    | '/api/contributions/upsert'
    | '/api/masjids/$masjidId'
    | '/api/masjids/search'
    | '/api/pmtiles/$archive'
    | '/api/qris-images/$qrisId'
    | '/api/turnstile/site-key'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/masjids/$masjidId/qris'
    | '/api/qris/$qrisId/reports'
    | '/api/admin/pending-qris/$qrisId/resolve'
    | '/api/admin/reports/$reportId/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiMasjidsRoute: typeof ApiMasjidsRouteWithChildren
  ApiAdminConfigHealthRoute: typeof ApiAdminConfigHealthRoute
  ApiAdminPendingQrisRoute: typeof ApiAdminPendingQrisRouteWithChildren
  ApiAdminQrisBackfillRoute: typeof ApiAdminQrisBackfillRoute
  ApiAdminReportsRoute: typeof ApiAdminReportsRouteWithChildren
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiContributionsUpsertRoute: typeof ApiContributionsUpsertRoute
  ApiPmtilesArchiveRoute: typeof ApiPmtilesArchiveRoute
  ApiQrisImagesQrisIdRoute: typeof ApiQrisImagesQrisIdRoute
  ApiTurnstileSiteKeyRoute: typeof ApiTurnstileSiteKeyRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
  ApiQrisQrisIdReportsRoute: typeof ApiQrisQrisIdReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masjids': {
      id: '/api/masjids'
      path: '/api/masjids'
      fullPath: '/api/masjids'
      preLoaderRoute: typeof ApiMasjidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turnstile/site-key': {
      id: '/api/turnstile/site-key'
      path: '/api/turnstile/site-key'
      fullPath: '/api/turnstile/site-key'
      preLoaderRoute: typeof ApiTurnstileSiteKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qris-images/$qrisId': {
      id: '/api/qris-images/$qrisId'
      path: '/api/qris-images/$qrisId'
      fullPath: '/api/qris-images/$qrisId'
      preLoaderRoute: typeof ApiQrisImagesQrisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pmtiles/$archive': {
      id: '/api/pmtiles/$archive'
      path: '/api/pmtiles/$archive'
      fullPath: '/api/pmtiles/$archive'
      preLoaderRoute: typeof ApiPmtilesArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masjids/search': {
      id: '/api/masjids/search'
      path: '/search'
      fullPath: '/api/masjids/search'
      preLoaderRoute: typeof ApiMasjidsSearchRouteImport
      parentRoute: typeof ApiMasjidsRoute
    }
    '/api/masjids/$masjidId': {
      id: '/api/masjids/$masjidId'
      path: '/$masjidId'
      fullPath: '/api/masjids/$masjidId'
      preLoaderRoute: typeof ApiMasjidsMasjidIdRouteImport
      parentRoute: typeof ApiMasjidsRoute
    }
    '/api/contributions/upsert': {
      id: '/api/contributions/upsert'
      path: '/api/contributions/upsert'
      fullPath: '/api/contributions/upsert'
      preLoaderRoute: typeof ApiContributionsUpsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports': {
      id: '/api/admin/reports'
      path: '/api/admin/reports'
      fullPath: '/api/admin/reports'
      preLoaderRoute: typeof ApiAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/qris-backfill': {
      id: '/api/admin/qris-backfill'
      path: '/api/admin/qris-backfill'
      fullPath: '/api/admin/qris-backfill'
      preLoaderRoute: typeof ApiAdminQrisBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pending-qris': {
      id: '/api/admin/pending-qris'
      path: '/api/admin/pending-qris'
      fullPath: '/api/admin/pending-qris'
      preLoaderRoute: typeof ApiAdminPendingQrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config-health': {
      id: '/api/admin/config-health'
      path: '/api/admin/config-health'
      fullPath: '/api/admin/config-health'
      preLoaderRoute: typeof ApiAdminConfigHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qris/$qrisId/reports': {
      id: '/api/qris/$qrisId/reports'
      path: '/api/qris/$qrisId/reports'
      fullPath: '/api/qris/$qrisId/reports'
      preLoaderRoute: typeof ApiQrisQrisIdReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masjids/$masjidId/qris': {
      id: '/api/masjids/$masjidId/qris'
      path: '/qris'
      fullPath: '/api/masjids/$masjidId/qris'
      preLoaderRoute: typeof ApiMasjidsMasjidIdQrisRouteImport
      parentRoute: typeof ApiMasjidsMasjidIdRoute
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports/$reportId/resolve': {
      id: '/api/admin/reports/$reportId/resolve'
      path: '/$reportId/resolve'
      fullPath: '/api/admin/reports/$reportId/resolve'
      preLoaderRoute: typeof ApiAdminReportsReportIdResolveRouteImport
      parentRoute: typeof ApiAdminReportsRoute
    }
    '/api/admin/pending-qris/$qrisId/resolve': {
      id: '/api/admin/pending-qris/$qrisId/resolve'
      path: '/$qrisId/resolve'
      fullPath: '/api/admin/pending-qris/$qrisId/resolve'
      preLoaderRoute: typeof ApiAdminPendingQrisQrisIdResolveRouteImport
      parentRoute: typeof ApiAdminPendingQrisRoute
    }
  }
}

interface ApiMasjidsMasjidIdRouteChildren {
  ApiMasjidsMasjidIdQrisRoute: typeof ApiMasjidsMasjidIdQrisRoute
}

const ApiMasjidsMasjidIdRouteChildren: ApiMasjidsMasjidIdRouteChildren = {
  ApiMasjidsMasjidIdQrisRoute: ApiMasjidsMasjidIdQrisRoute,
}

const ApiMasjidsMasjidIdRouteWithChildren =
  ApiMasjidsMasjidIdRoute._addFileChildren(ApiMasjidsMasjidIdRouteChildren)

interface ApiMasjidsRouteChildren {
  ApiMasjidsMasjidIdRoute: typeof ApiMasjidsMasjidIdRouteWithChildren
  ApiMasjidsSearchRoute: typeof ApiMasjidsSearchRoute
}

const ApiMasjidsRouteChildren: ApiMasjidsRouteChildren = {
  ApiMasjidsMasjidIdRoute: ApiMasjidsMasjidIdRouteWithChildren,
  ApiMasjidsSearchRoute: ApiMasjidsSearchRoute,
}

const ApiMasjidsRouteWithChildren = ApiMasjidsRoute._addFileChildren(
  ApiMasjidsRouteChildren,
)

interface ApiAdminPendingQrisRouteChildren {
  ApiAdminPendingQrisQrisIdResolveRoute: typeof ApiAdminPendingQrisQrisIdResolveRoute
}

const ApiAdminPendingQrisRouteChildren: ApiAdminPendingQrisRouteChildren = {
  ApiAdminPendingQrisQrisIdResolveRoute: ApiAdminPendingQrisQrisIdResolveRoute,
}

const ApiAdminPendingQrisRouteWithChildren =
  ApiAdminPendingQrisRoute._addFileChildren(ApiAdminPendingQrisRouteChildren)

interface ApiAdminReportsRouteChildren {
  ApiAdminReportsReportIdResolveRoute: typeof ApiAdminReportsReportIdResolveRoute
}

const ApiAdminReportsRouteChildren: ApiAdminReportsRouteChildren = {
  ApiAdminReportsReportIdResolveRoute: ApiAdminReportsReportIdResolveRoute,
}

const ApiAdminReportsRouteWithChildren = ApiAdminReportsRoute._addFileChildren(
  ApiAdminReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiMasjidsRoute: ApiMasjidsRouteWithChildren,
  ApiAdminConfigHealthRoute: ApiAdminConfigHealthRoute,
  ApiAdminPendingQrisRoute: ApiAdminPendingQrisRouteWithChildren,
  ApiAdminQrisBackfillRoute: ApiAdminQrisBackfillRoute,
  ApiAdminReportsRoute: ApiAdminReportsRouteWithChildren,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiContributionsUpsertRoute: ApiContributionsUpsertRoute,
  ApiPmtilesArchiveRoute: ApiPmtilesArchiveRoute,
  ApiQrisImagesQrisIdRoute: ApiQrisImagesQrisIdRoute,
  ApiTurnstileSiteKeyRoute: ApiTurnstileSiteKeyRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
  ApiQrisQrisIdReportsRoute: ApiQrisQrisIdReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
